version: '1.0'

services:
  report-app-service:
    container_name: report-app-service_container
    image: report-app-service
    build: .
    ports:
      - 8000-8999:8080 # Expose port 8080
    restart: always  
    environment:
      DATABASE_URL: jdbc:postgresql://report-app-db_container:5432/report_database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: secret_password
    depends_on:
      - report-app-db
    volumes:
      - C:\Users\alman\Repository\backend-report-app\src\main\resources\csv:/app/csv
      - C:\Users\alman\Repository\backend-report-app\src\main\resources\firebase:/app/firebase

  report-app-db:
    container_name: report-app-db_container
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: report_database
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:    