server:
  port: 9999

spring-doc:
  swagger-ui:
    path: /docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/report-app-db?useSSL=false&serverTimezone=UTC
    username: root
    password: coffee2sweet
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update